apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongodb-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80